In [1]:
%load_ext autoreload

%autoreload 2

In [2]:
%load_ext line_profiler
%load_ext memory_profiler
%load_ext Cython

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
import sys, argparse, logging
import pymssql
import _mssql
from datetime import datetime, time
from decimal import Decimal
import pymongo
from pymongo import MongoClient
from tqdm import tqdm, tnrange, tqdm_notebook
import pandas as pd
from tmqr.settings import *
from tmqrfeed.assetsession import AssetSession
import pickle
import pytz
try:
    from tmqr.settings_local import *
except:
    pass

from tmqrfeed.datafeed import DataFeed



In [5]:
# Init mongo asset index
client = MongoClient(MONGO_CONNSTR)
mongo_db = client[MONGO_DB]


In [6]:
session_settings = [{
                                    'decision': '10:40',
                                    'dt': datetime(1900, 1, 1),
                                    'execution': '10:45',
                                    'start': '00:32'},

                                {
                                    'decision': '11:40',
                                    'dt': datetime(2011, 9, 30),
                                    'execution': '11:45',
                                    'start': '01:32'},

                                {
                                    'decision': '12:40',
                                    'dt': datetime(2012, 1, 1),
                                    'execution': '12:45',
                                    'start': '02:32'},
                                ]
tz = pytz.timezone('US/Pacific')
sess = AssetSession(session_settings, tz)

In [7]:
feed = DataFeed()

In [8]:
def load_case1():
    dframes_list = []
    for data in mongo_db['quotes_intraday'].find({'tckr': 'US.F.CL.Q12.120720'}):
        df = pickle.loads(data['ohlc'])
        dframes_list.append(df)    

    result = pd.concat(dframes_list)

In [9]:
def load_case2():
    result_df = pd.DataFrame()
    for data in mongo_db['quotes_intraday'].find({'tckr': 'US.F.CL.Q12.120720'}):
        df = pickle.loads(data['ohlc'])
        result_df = pd.concat([result_df, df])    

    return result_df

In [10]:
%timeit load_case1()

10 loops, best of 3: 162 ms per loop


In [11]:
%timeit load_case2()

1 loop, best of 3: 341 ms per loop


In [ ]:
%lprun -f load_case1 load_case1()

In [18]:
%lprun -f load_case2 load_case2()

In [15]:
df = load_case2()
df.tz_convert('US/Pacific', copy=False)

o       h       l       c      v
dt                                                              
2011-07-11 11:29:00-07:00  100.26  100.26  100.26  100.26    0.0
2011-07-12 11:29:00-07:00  101.88  101.88  101.88  101.88    0.0
2011-07-13 11:29:00-07:00  102.70  102.70  102.70  102.70    0.0
2011-07-14 08:44:00-07:00  101.31  101.31  101.31  101.31    1.0
2011-07-14 08:50:00-07:00  101.30  101.30  101.30  101.30    1.0
2011-07-14 09:34:00-07:00  100.89  100.89  100.89  100.89    1.0
2011-07-14 10:31:00-07:00  100.51  100.61  100.51  100.61    3.0
2011-07-14 10:33:00-07:00  100.43  100.43  100.30  100.30    3.0
2011-07-14 10:34:00-07:00  100.25  100.25  100.25  100.25    1.0
2011-07-14 10:35:00-07:00  100.16  100.16  100.16  100.16    1.0
2011-07-14 11:29:00-07:00  100.85  100.85  100.85  100.85    0.0
2011-07-15 11:29:00-07:00  101.88  101.88  101.88  101.88    0.0
2011-07-18 11:29:00-07:00  100.66  100.66  100.66  100.66    0.0
2011-07-19 11:29:00-07:00  102.00  102.00  102.00  102.00    0.0
2011-07-20 11:29:00-07:00  102.48  102.48  102.48  102.48    0.0
2011-07-21 11:29:00-07:00  102.80  102.80  102.80  102.80    0.0
2011-07-22 11:29:00-07:00  103.18  103.18  103.18  103.18    0.0
2011-07-25 09:50:00-07:00  102.58  102.58  102.58  102.58    1.0
2011-07-25 11:29:00-07:00  102.93  102.93  102.93  102.93    0.0
2011-07-26 06:44:00-07:00  101.88  101.88  101.88  101.88    2.0
2011-07-26 09:12:00-07:00  103.92  103.92  103.92  103.92    1.0
2011-07-26 11:29:00-07:00  103.32  103.32  103.32  103.32    0.0
2011-07-27 11:29:00-07:00  101.62  101.62  101.62  101.62    0.0
2011-07-28 11:29:00-07:00  101.76  101.76  101.76  101.76    0.0
2011-07-29 06:49:00-07:00  100.12  100.13  100.12  100.12    5.0
2011-07-29 11:29:00-07:00  100.10  100.10  100.10  100.10    0.0
2011-07-29 12:08:00-07:00  100.15  100.15  100.15  100.15    1.0
2011-08-01 06:05:00-07:00  101.85  101.85  101.85  101.85    1.0
2011-08-01 07:00:00-07:00  101.78  101.78  101.19  101.19    3.0
2011-08-01 07:01:00-07:00  101.27  101.33  101.27  101.28    3.0
...                           ...     ...     ...     ...    ...
2012-07-20 11:00:00-07:00   91.50   91.50   91.42   91.45   88.0
2012-07-20 11:01:00-07:00   91.45   91.49   91.44   91.48   89.0
2012-07-20 11:02:00-07:00   91.49   91.54   91.49   91.54   78.0
2012-07-20 11:03:00-07:00   91.56   91.67   91.56   91.66   97.0
2012-07-20 11:04:00-07:00   91.67   91.67   91.57   91.59   97.0
2012-07-20 11:05:00-07:00   91.58   91.61   91.57   91.61  120.0
2012-07-20 11:06:00-07:00   91.63   91.67   91.61   91.63   69.0
2012-07-20 11:07:00-07:00   91.66   91.66   91.53   91.53  123.0
2012-07-20 11:08:00-07:00   91.55   91.55   91.52   91.55   60.0
2012-07-20 11:09:00-07:00   91.55   91.58   91.53   91.54   71.0
2012-07-20 11:10:00-07:00   91.55   91.59   91.53   91.54   66.0
2012-07-20 11:11:00-07:00   91.55   91.58   91.54   91.55   46.0
2012-07-20 11:12:00-07:00   91.56   91.56   91.51   91.53  146.0
2012-07-20 11:13:00-07:00   91.51   91.57   91.47   91.54   76.0
2012-07-20 11:14:00-07:00   91.55   91.57   91.54   91.54   86.0
2012-07-20 11:15:00-07:00   91.55   91.55   91.48   91.49   95.0
2012-07-20 11:16:00-07:00   91.49   91.49   91.39   91.39  130.0
2012-07-20 11:17:00-07:00   91.39   91.39   91.26   91.33  272.0
2012-07-20 11:18:00-07:00   91.30   91.43   91.28   91.41  201.0
2012-07-20 11:19:00-07:00   91.42   91.46   91.39   91.40  111.0
2012-07-20 11:20:00-07:00   91.39   91.42   91.26   91.26  129.0
2012-07-20 11:21:00-07:00   91.26   91.26   91.16   91.20  151.0
2012-07-20 11:22:00-07:00   91.20   91.23   91.18   91.23  124.0
2012-07-20 11:23:00-07:00   91.24   91.35   91.22   91.30   88.0
2012-07-20 11:24:00-07:00   91.29   91.42   91.27   91.42   79.0
2012-07-20 11:25:00-07:00   91.40   91.40   91.36   91.39   56.0
2012-07-20 11:26:00-07:00   91.38   91.47   91.37   91.43  119.0
2012-07-20 11:27:00-07:00   91.40   91.42   91.34   91.42   98.0
2012-07-20 11:28:00-07:00   91.42   91.55   91.42   91.54  104.0
20

In [28]:
%mprun -f df.tz_convert df.tz_convert('US/Pacific', copy=True)

In [13]:
dt1 = df.index[-1]


In [14]:
%lprun -f sess.date_is_insession df.index.map(lambda x: sess.date_is_insession(x))

In [14]:
%lprun -f sess.date_is_insession sess.date_is_insession(dt1)

In [17]:
%timeit df.between_time('9:30', '10:45')

100 loops, best of 3: 5.39 ms per loop


In [15]:
%timeit df.index.map(lambda x: sess.date_is_insession(x))

1 loop, best of 3: 1.22 s per loop


In [25]:
%mprun -f sess.filter_dataframe sess.filter_dataframe(df)

In [23]:
%timeit sess.filter_dataframe(df)

100 loops, best of 3: 8.92 ms per loop


In [19]:
date_start = datetime(2012, 1, 1)
date_end = datetime(2013, 1, 1)

%timeit df[(df.index >= date_start) & (df.index < date_end)]

100 loops, best of 3: 3.49 ms per loop


In [22]:
%timeit df.ix[date_start:date_end]

1000 loops, best of 3: 504 µs per loop


In [49]:
pd.Timestamp(np_date).date()

datetime.date(2011, 7, 11)

In [28]:
def datetime64_to_time_of_day(datetime64_array):
    """
    Return a new array. For every element in datetime64_array return the time of day (since midnight).
    >>> datetime64_to_time_of_day(np.array(['2012-01-02T01:01:01.001Z'],dtype='datetime64[ms]'))
    array([3661001], dtype='timedelta64[ms]')
    >>> datetime64_to_time_of_day(np.datetime64('2012-01-02T01:01:01.001Z','[ms]'))
    numpy.timedelta64(3661001,'ms')
    """
    day = datetime64_array.astype('datetime64[D]').astype(datetime64_array.dtype)
    time_of_day = datetime64_array - day
    return time_of_day

In [30]:
%timeit datetime64_to_time_of_day(df.index.values)

100 loops, best of 3: 3.88 ms per loop


In [40]:
(datetime(2010, 1, 1, 18, 29) - datetime(2010, 1, 1)).seconds * 1000000000

66540000000000

In [32]:
 datetime64_to_time_of_day(df.index.values)

array([66540000000000, 66540000000000, 66540000000000, ..., 66420000000000,
       66480000000000, 66540000000000], dtype='timedelta64[ns]')

In [41]:
np.datetime64(datetime(2011, 1,1))

numpy.datetime64('2011-01-01T00:00:00.000000')

In [119]:
sess_params = [x for x in sess.sessions]

In [120]:
sess_params

[{'decision': datetime.time(10, 40, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'dt': datetime.datetime(1900, 1, 1, 0, 0, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'execution': datetime.time(10, 45, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'start': datetime.time(0, 32, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)},
 {'decision': datetime.time(11, 40, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'dt': datetime.datetime(2011, 9, 30, 0, 0, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'execution': datetime.time(11, 45, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'start': datetime.time(1, 32, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)},
 {'decision': datetime.time(12, 40, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'dt': datetime.datetime(2012, 1, 1, 0, 0, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'execution': datetime.time(12, 45, tz

In [78]:
%%cython -a
import numpy as np
import pandas as pd
from datetime import datetime

def filter_index(self, dataframe_index, sess_params):
    """
    Creates boolean filter array used to filter dataframe from out-of-session datapoints
    :param dataframe_index:
    :return:
    """

    flt = np.empty(len(dataframe_index))
    flt.fill(False)
    start_time = 0
    end_time = 0
    next_sess_date = 0

    
    date_array = dataframe_index.values
    time_array = date_array.view('datetime64[D]')
    
    date = date_array[0]
    for sess_idx, sess in enumerate(reversed(sess_params)):
        if date >= sess['dt']:
            start_datetime = np.datetime64(datetime.combine(date, sess['start']))
            end_datetime = np.datetime64(datetime.combine(date, sess['decision']))
            
            

            if sess_idx > 0:
                next_sess_date = np.datetime64(sess_params[len(sess_params) - sess_idx]['dt'])
            else:
                next_sess_date = 0
    
        
    for i in range(len(dataframe_index)):
        dt = date_array[i]
        t = time_array[i]

        if t >= start_time and t <= end_time:
            flt[i] = 1

    return flt

In [64]:
sess_params[0]['start']

ValueError: Could not convert object to NumPy datetime

In [74]:
%timeit df.index.values.astype('datetime64[D]')

1000 loops, best of 3: 1.94 ms per loop


In [75]:
%timeit df.index.values.view('datetime64[D]')

The slowest run took 11.83 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.48 µs per loop


In [79]:
dt = df.index.values

In [83]:
date_arr = dt.astype('datetime64[D]').view('uint64')

In [84]:
date_arr

array([15166, 15167, 15168, ..., 15541, 15541, 15541], dtype=uint64)

In [85]:
date_arr2 = dt.view('uint64')

In [86]:
date_arr2

array([1310408940000000000, 1310495340000000000, 1310581740000000000, ...,
       1342808820000000000, 1342808880000000000, 1342808940000000000], dtype=uint64)

In [95]:
datetime.fromtimestamp(, tz=pytz.timezone("UTC"))

datetime.datetime(2011, 7, 12, 18, 29, tzinfo=<UTC>)

In [123]:
sess_params

[{'decision': datetime.time(10, 40, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'dt': datetime.datetime(1900, 1, 1, 0, 0, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'execution': datetime.time(10, 45, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'start': datetime.time(0, 32, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)},
 {'decision': datetime.time(11, 40, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'dt': datetime.datetime(2011, 9, 30, 0, 0, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'execution': datetime.time(11, 45, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'start': datetime.time(1, 32, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)},
 {'decision': datetime.time(12, 40, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'dt': datetime.datetime(2012, 1, 1, 0, 0, tzinfo=<DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>),
  'execution': datetime.time(12, 45, tz

In [132]:
def sess_filt():
    df_list = []
    for i in range(1, len(sess_params)):
        if i < len(sess_params)-1:
            date_start = sess_params[i-1]['dt']
            date_end = sess_params[i]['dt']
            time_start = sess_params[i-1]['start']
            time_end = sess_params[i-1]['decision']
        else:
            date_start = sess_params[i-1]['dt']        
            date_end = datetime(2100, 1, 1)        
            time_start = sess_params[i-1]['start']
            time_end = sess_params[i-1]['decision']

        print('DateStart: {0} DateEnd: {1}'.format(date_start, date_end))
        print('TimeStart: {0} TimeEnd: {1}'.format(time_start, time_end))
        tmp_df = df[(df.index >= date_start) & (df.index < date_end)]
        df_list.append(tmp_df.between_time(time_start, time_end))

    df_sess = pd.concat(df_list)

In [133]:
%timeit sess_filt()

DateStart: 1900-01-01 00:00:00-07:53 DateEnd: 2011-09-30 00:00:00-07:53
TimeStart: 00:32:00 TimeEnd: 10:40:00
DateStart: 2011-09-30 00:00:00-07:53 DateEnd: 2100-01-01 00:00:00
TimeStart: 01:32:00 TimeEnd: 11:40:00
DateStart: 1900-01-01 00:00:00-07:53 DateEnd: 2011-09-30 00:00:00-07:53
TimeStart: 00:32:00 TimeEnd: 10:40:00
DateStart: 2011-09-30 00:00:00-07:53 DateEnd: 2100-01-01 00:00:00
TimeStart: 01:32:00 TimeEnd: 11:40:00
DateStart: 1900-01-01 00:00:00-07:53 DateEnd: 2011-09-30 00:00:00-07:53
TimeStart: 00:32:00 TimeEnd: 10:40:00
DateStart: 2011-09-30 00:00:00-07:53 DateEnd: 2100-01-01 00:00:00
TimeStart: 01:32:00 TimeEnd: 11:40:00
DateStart: 1900-01-01 00:00:00-07:53 DateEnd: 2011-09-30 00:00:00-07:53
TimeStart: 00:32:00 TimeEnd: 10:40:00
DateStart: 2011-09-30 00:00:00-07:53 DateEnd: 2100-01-01 00:00:00
TimeStart: 01:32:00 TimeEnd: 11:40:00
DateStart: 1900-01-01 00:00:00-07:53 DateEnd: 2011-09-30 00:00:00-07:53
TimeStart: 00:32:00 TimeEnd: 10:40:00
DateStart: 2011-09-30 00:00:00-07:

In [135]:
df.index.tz

<UTC>